question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'DragonForce\'s "Through the Fire and Flames" is widely considered to be the hardest song in the Guitar Hero series.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'The Ace Attorney trilogy was suppose to end with "Phoenix Wright: Ace Attorney - Trials and Tribulations" as its final game.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": '"Metal Gear Solid 3: Snake Eater" takes place on Shadow Moses Island.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Tony Hawk's Pro Skater was released in 1999.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In "Overwatch," an allied McCree will say "Step right up" upon using his ultimate ability Deadeye.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In "Team Fortress 2", the "Bill\'s Hat" is a reference to the game "Dota 2".',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In "Super Mario World", the rhino mini-boss, Reznor, is named after the lead singer of the band "Nine Inch Nails".',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In "Call Of Duty: Zombies", you can upgrade the "Apothicon Servant" in the "Shadows Of Evil" map.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'The Fiat Multipla is a drivable car in "Forza Horizon 3".',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": '"Return to Castle Wolfenstein" was the only game of the Wolfenstein series where you don\'t play as William "B.J." Blazkowicz.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'The scrapped Sonic the Hedgehog 2 level "Hidden Palace Zone" was later reused in the iOS port of the game. ',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In the game "Until Dawn" Emily is the only playable character who can be killed by another playable character directly.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": 'In "Resident Evil", only Chris has access to the grenade launcher.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
